import React from "react";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { useEffect } from "react";
import axios from "axios";
import { AudioOutlined } from '@ant-design/icons';
import { Input, Space } from 'antd';
import searchResults from "../../../pages/searchresults";
import { useRouter } from 'next/router';
import { Image } from 'antd';
const { Search } = Input;
const suffix = (
  <AudioOutlined
    style={{
      fontSize: 16,
      color: '#1890ff',
    }}
  />
);
// const onSearch = (value) => {
//   <searchResults
//   props = {{
//     query: value,
//   }}

//   />
//   console.log(value);
// }

// const onSearch = (value) => {
//   return <searchResults query={value} />
// }

// const onSearch = (value) => {
//   const router = useRouter();
//   router.push({
//     pathname: '/searchresults',
//     query: { query: value },
//   });
// }

import MainNav from "./MainNav";

const Header = () => {
  const [Categories, setCategories] = useState();
  const [query, setQuery] = useState("");

  const getData = async () => {
    // Get Posts
    await axios
      .get(`${process.env.NEXT_PUBLIC_BACKEND_API}seekcategories?per_page=4`)
      .then((result) => setCategories(result.data))
      //   .then((result) => console.log(result.data))
      .catch(function (error) {
        if (error.response) {
          // Request made and server responded
          // console.log(error.response.data);
          // console.log(error.response.status);
          // console.log(error.response.headers);
        } else if (error.request) {
          // The request was made but no response was received
          // console.log(error.request);
        } else {
          // Something happened in setting up the request that triggered an Error
          // console.log("Error", error.message);
        }
      });
  };

  useEffect(() => {
    getData();
  }, []);

  function handleKeyPress(event) {
    if (event.key === 'Enter') {
      performSearch()
    }
  }

  function performSearch() {
    window.location.href = `/searchresults?query=${query}`
  }

  return (
    <>
      <Head>
        {/* <title>Create Next App</title>   */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://img.icons8.com/ios-glyphs/30/000000/search-more.png" />
      </Head>
      <header class="site-navbar" role="banner">
        <div class="container-fluid">
          <div class="row align-items-center">
            <div class="col-12 col-md-4 site-logo">
              <Link href="/" legacyBehavior>
                <a class="text-black h2 mb-0">
                  <Image
                    width={200}
                    src="/wordpress tutorial for beginners.png"
                  />
                  {/* Seek WordPress */}
                </a>
              </Link>
            </div>
            <div class="col-12 col-md-6 text-right">
              <MainNav />
              <a
                href="#"
                class="site-menu-toggle js-menu-toggle text-black d-inline-block d-lg-none"
              >
                <span class="icon-menu h3"></span>
              </a>
            </div>
            <div class="col-12 col-md-2">
              <div
                style={{
                  "display": "flex"
                }}
              >
                <Input
                  placeholder="search"
                  onChange={(event) => {
                    setQuery(event.target.value)
                  }}
                  onKeyPress={handleKeyPress}
                  style={{
                    width: 200,
                  }}
                />
                <Link href={`/searchresults?query=${query}`} legacyBehavior>
                  <a onClick={performSearch}>Search</a>
                </Link>
              </div>
            </div>
          </div>

        </div>
      </header>
    </>
  );
};

export default Header;
